apiVersion: batch/v1
kind: Job
metadata:
  name: ml-generator-job-ds1
  namespace: rogeroliveira
spec:
  template:
    metadata:
      name: ml-generator-pod
    spec:
      containers:
      - name: ml-container
        image: rogerdornas/playlist-ml:v1.0
        command: ["/bin/sh", "-c"]
        args: ["python generator.py && cp model.pkl /shared/model.pkl && echo 'Modelo salvo!'"]
        volumeMounts:
        - name: shared-storage
          mountPath: /shared
        - name: dataset-storage
          mountPath: /home/datasets/spotify
          readOnly: true
      restartPolicy: OnFailure
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: model-pvc
      - name: dataset-storage
        hostPath:
          path: /home/datasets/spotify
          type: Directory
